# Docker/Dockerfile.dev
FROM node:20-alpine
WORKDIR /app
RUN apk add --no-cache libc6-compat

# copy package files trước để cache layer cài deps
COPY package*.json ./

# dùng npm install cho môi trường DEV (bỏ qua lock mismatch)
RUN npm install

# copy nốt source (sẽ bị volume mount đè khi up)
COPY . .

ENV NODE_ENV=development
ENV HOSTNAME=0.0.0.0
ENV CHOKIDAR_USEPOLLING=true
ENV WATCHPACK_POLLING=true

EXPOSE 3000 9229
CMD ["npm", "run", "dev"]
